import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

const source = readFileSync(new URL('../app/careers/[slug]/ApplicationForm.tsx', import.meta.url), 'utf8')

assert.match(source, /isRoleOpenForApplications\(role\)/)
assert.match(source, /disabled=\{!isOpen \|\| status === 'submitting'\}/)
assert.match(source, /Applications for this role closed on \{role\.closingDate\}\./)
assert.match(source, /Applications closed/)
assert.match(source, /Applications for this role are now closed\./)
assert.match(source, /refreshAvailability/)
assert.match(source, /60_000/)
assert.match(source, /Please confirm you have read and understood the Privacy Notice before submitting\./)
assert.match(source, /I confirm that I have read and understood the\{' '\}/)
assert.match(source, />\s*Privacy Notice\s*</)
assert.match(source, /Date of Birth \*<input name="dateOfBirth" type="date" required/)
assert.match(source, /dateOfBirth: String\(formData\.get\('dateOfBirth'\)/)
assert.match(source, /<input name="consent" type="checkbox" required/)
assert.match(source, /href="\/privacy"/)
assert.doesNotMatch(source, /I agree NGH may store my application data for recruitment purposes/)
assert.doesNotMatch(source, /I consent to NGH Property Group processing my application data/)
assert.doesNotMatch(source, /Please accept the required privacy consent before submitting\./)
assert.doesNotMatch(source, /I&apos;d also like to receive occasional updates/)
assert.doesNotMatch(source, /also like to receive occasional updates/)
assert.doesNotMatch(source, /We delete your application data within 28 days/)
assert.doesNotMatch(source, /The Worker stores the application securely, alerts our recruiting team in Telegram, and the Mini mailer sends the durable email from our own mail server\./)
assert.match(source, /Secure application/)
assert.match(source, /Apply for \{role\.title\}/)

const privacy = readFileSync(new URL('../app/privacy-policy/page.tsx', import.meta.url), 'utf8')
assert.match(privacy, /Controller: PT Next Gen Home, Bali, Indonesia\. These roles are based in Indonesia and this careers page is not specifically directed at residents of the EU\. Contact: info@nghpropertygroup\.com\./)
assert.match(privacy, /What we collect: your name, date of birth, email, phone\/WhatsApp, location, LinkedIn\/portfolio URL, salary expectation, experience, motivation, tools & AI usage, CV, intro video, and answers to role-specific questions\. For bot\/abuse prevention we also process your IP address via Cloudflare Turnstile\./)
assert.doesNotMatch(privacy, /What we collect: your name, email, phone\/WhatsApp/)
assert.match(privacy, /We do not rely on consent to process your application\./)
assert.match(privacy, /Telegram \(internal \\\"new application\\\" alert, link\/reference only, no candidate data in the message\)/)
assert.match(privacy, /Your rights: you may request access, correction, deletion, restriction and portability of your data, and object to the processing;/)
assert.doesNotMatch(privacy, /NGH Nexa social media operations/)

const scrollExperience = readFileSync(new URL('../components/ScrollExperience.tsx', import.meta.url), 'utf8')
assert.match(scrollExperience, /\{ label: 'Contact', href: '#contact' \},\n\s*\{ label: 'Careers', href: '\/careers' \},/)
assert.match(scrollExperience, /\{ label: 'Privacy', href: '\/privacy' \}/)
assert.match(scrollExperience, /src="\/images\/mitchell-founder-fill\.jpg"[\s\S]*?className="object-cover"/)
assert.equal(existsSync(new URL('../public/images/mitchell-founder-fill.jpg', import.meta.url)), true)
assert.match(scrollExperience, /Sergio', role: 'Strategic Partner', image: '\/images\/sergio\.jpg'/)
assert.match(scrollExperience, /Lucy Leanatan', role: 'Marketing Manager', image: '\/images\/lucy-leanatan\.jpeg'/)
assert.match(scrollExperience, /Richard Argapara', role: 'Financial Manager', image: '\/images\/richard-argapara\.jpeg'/)
assert.match(scrollExperience, /Steven Tan-a-Kiam', role: 'Investor & Strategic Coach', image: '\/images\/steven-tan-a-kiam\.jpeg'/)
assert.match(scrollExperience, /className="object-cover"\n\s*sizes="200px"/)
assert.doesNotMatch(scrollExperience, /objectPosition: 'center 20%'|scale\(1\.25\)/)
assert.equal(existsSync(new URL('../public/images/sergio.jpg', import.meta.url)), true)
assert.equal(existsSync(new URL('../public/images/lucy-leanatan.jpeg', import.meta.url)), true)
assert.equal(existsSync(new URL('../public/images/richard-argapara.jpeg', import.meta.url)), true)
assert.equal(existsSync(new URL('../public/images/steven-tan-a-kiam.jpeg', import.meta.url)), true)

const careersConfig = readFileSync(new URL('../data/careers.ts', import.meta.url), 'utf8')
assert.match(careersConfig, /roleCode: 'OPM'/)
assert.match(careersConfig, /closingDate: '2026-07-20'/)
assert.match(careersConfig, /Salary: IDR 6,000,000 — 9,000,000 per month based on experience/)
assert.match(careersConfig, /As our Operations & Planning Manager, you'll coordinate daily operations across multiple projects, keep teams aligned, manage timelines and deadlines, and ensure execution happens at the highest standard\./)
assert.match(careersConfig, /This role is ideal for someone with experience in operations, project management, construction coordination, or real estate development who thrives in a fast-paced environment\./)
assert.match(careersConfig, /Open to Indonesian nationals — based in or willing to relocate to Bali, and fluent in English/)
assert.doesNotMatch(careersConfig, /'Fluent in English'/)
assert.doesNotMatch(careersConfig, /'Based in or willing to relocate to Bali'/)
assert.doesNotMatch(careersConfig, /roleOverview/)
assert.match(careersConfig, /Send your CV and a short motivation to the NGH Property Group team\. Position starts immediately\./)
assert.doesNotMatch(careersConfig, /Dutch Standard|Dutch Governance/)
assert.doesNotMatch(careersConfig, /roleCode: 'FSD'/)
assert.doesNotMatch(careersConfig, /roleCode: 'GEN'/)
assert.doesNotMatch(careersConfig, /full-stack-developer/)
assert.doesNotMatch(careersConfig, /open-application/)
assert.match(careersConfig, /roleCode: string/)
const careersListing = readFileSync(new URL('../app/careers/page.tsx', import.meta.url), 'utf8')
assert.match(careersListing, /import \{ careerRoles, isRoleOpenForApplications \} from '@\/data\/careers'/)
assert.match(careersListing, /const roles = careerRoles/)
assert.doesNotMatch(careersListing, /getOpenCareerRoles/)
assert.match(careersListing, /Applications closed/)
assert.match(careersListing, /Role close date:/)
assert.doesNotMatch(readFileSync(new URL('../app/careers/[slug]/page.tsx', import.meta.url), 'utf8'), />\s*The Role\s*</)

const headersUrl = new URL('../public/_headers', import.meta.url)
assert.equal(existsSync(headersUrl), true)
const headers = readFileSync(headersUrl, 'utf8')
assert.match(headers, /\/\*\s*\n\s*Referrer-Policy:\s*no-referrer/)

const redirects = readFileSync(new URL('../public/_redirects', import.meta.url), 'utf8')
assert.match(redirects, /\/careers\/full-stack-developer \/careers 301!/) 
assert.match(redirects, /\/careers\/open-application \/careers 301!/)

console.log('careers legal copy ok')
